services:
    db:
        image: 'postgres:17'
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'pgsql-data:/var/lib/postgresql/data'
            - './docker/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'

    redis:
        image: 'redis'
        ports:
            - '${REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    pgsql-data: {}
    redis-data: {}
